import { WINDOW_SIZE } from './WindowSize';

export const FONT_SIZE = {
  CONTENTS_TITLE: 26 * WINDOW_SIZE.HEIGHT_WEIGHT,
  SMALL_TITLE: 20 * WINDOW_SIZE.HEIGHT_WEIGHT,
  SMALL_DESCRIPTION: 12 * WINDOW_SIZE.HEIGHT_WEIGHT,
  INPUT_TEXT: 14 * WINDOW_SIZE.HEIGHT_WEIGHT,
  BOLD_LABEL: 26 * WINDOW_SIZE.HEIGHT_WEIGHT,
  BACK_ARROW: 22 * WINDOW_SIZE.WIDTH_WEIGHT,
};
