export const INPUT_PHONE_STATUS = {
  NONE: 'NONE',
  PHONE_NUMBER_NOT_FORMATTED: 'PHONE_NUMBER_NOT_FORMATTED',
  PHONE_NUMBER_ALREADY_EXISTED: 'PHONE_NUMBER_ALREADY_EXISTED',
  PHONE_NUMBER_FORMATTED: 'PHONE_NUMBER_FORMATTED',
  PHONE_CODE_NOT_FORMATTED: 'PHONE_CODE_NOT_FORMATTED',
  PHONE_CODE_FORMATTED: 'PHONE_CODE_FORMATTED',
  PHONE_CODE_NOT_VALID: 'PHONE_CODE_NOT_VALID',
  SUCCEED: 'SUCCEED'
};
