export const SIGN_VIEW_STATUS = {
  NONE: 'NONE',
  SIGN_IN_STARTED: 'SIGN_IN_STARTED',
  SIGN_UP_STARTED: 'SIGN_UP_STARTED',
  EMAIL_COMPLETED: 'EMAIL_COMPLETED',
  PASSWORD_COMPLETED: 'PASSWORD_COMPLETED',
  NAME_COMPLETED: 'NAME_COMPLETED',
  GENDER_COMPLETED: 'GENDER_COMPLETED',
  PHONE_COMPLETED: 'PHONE_COMPLETED'
};
