export const SIGN_VIEW_STATUS = {
  NONE: 'NONE',
  SIGN_IN_STARTED: 'SIGN_IN_STARTED',
  SIGN_UP_STARTED: 'SIGN_UP_STARTED',
  EMAIL_COMPLETED: 'EMAIL_COMPLETED',
  PASSWORD_COMPLETED: 'PASSWORD_COMPLETED',
  BASIC_INFO_COMPLETED: 'BASIC_INFO_COMPLETED',
  PHONE_COMPLETED: 'PHONE_COMPLETED',
};
