export const SIGN_UP_PHONE_VIEW_STATUS = {
  PHONE_NUMBER_SENT_BEFORE: 'PHONE_NUMBER_SENT_BEFORE',
  PHONE_NUMBER_SENT_AFTER: 'PHONE_NUMBER_SENT_AFTER',
  PHONE_VALIDATION_SUCCEED: 'PHONE_VALIDATION_SUCCEED'
};
